defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 1
  working_directory: ~/ember-trivia

version: 2.1

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate reports folder
          command: mkdir -p ./reports
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - ember-trivia-node10-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --non-interactive --pure-lockfile
      - save_cache:
          key: ember-trivia-node10-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/ember-trivia/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Handlebars
          command: yarn lint:hbs
      - run:
          name: Lint JavaScript
          command: yarn lint:js

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test
      - store_test_results:
          path: './reports'
      - store_artifacts:
          path: './reports'

workflows:
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
